# Generated by Django 5.1 on 2024-08-23 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Highschool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CollegeStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], max_length=20)),
                ('MOD_QUANTITATIVE_REASONING', models.FloatField()),
                ('MOD_WRITTEN_COMMUNICATION', models.FloatField()),
                ('MOD_CRITICAL_READING', models.FloatField()),
                ('MOD_ENGLISH', models.FloatField()),
                ('MOD_CITIZENSHIP_COMPETENCES', models.FloatField()),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_students', to='saber.college')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HighschoolStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], max_length=20)),
                ('PUNT_ENGLISH', models.FloatField()),
                ('PUNT_MATHEMATICS', models.FloatField()),
                ('PUNT_SOCIAL_CITIZENSHIP', models.FloatField()),
                ('PUNT_NATURAL_SCIENCES', models.FloatField()),
                ('PUNT_CRITICAL_READING', models.FloatField()),
                ('PUNT_GLOBAL', models.FloatField()),
                ('highschool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highschool_students', to='saber.highschool')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', to='saber.department')),
            ],
        ),
        migrations.AddField(
            model_name='highschool',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highschools', to='saber.municipality'),
        ),
        migrations.AddField(
            model_name='college',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colleges', to='saber.municipality'),
        ),
    ]
