# Generated by Django 5.1 on 2024-08-21 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StudentResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('municipalities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='saber.municipality')),
            ],
        ),
        migrations.CreateModel(
            name='Saber11Results',
            fields=[
                ('studentresults_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='saber.studentresults')),
                ('PUNT_ENGLISH', models.FloatField()),
                ('PUNT_MATHEMATICS', models.FloatField()),
                ('PUNT_SOCIAL_CITIZENSHIP', models.FloatField()),
                ('PUNT_NATURAL_SCIENCES', models.FloatField()),
                ('PUNT_CRITICAL_READING', models.FloatField()),
                ('PUNT_GLOBAL', models.FloatField()),
            ],
            bases=('saber.studentresults',),
        ),
        migrations.CreateModel(
            name='SaberProResults',
            fields=[
                ('studentresults_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='saber.studentresults')),
                ('MOD_QUANTITATIVE_REASONING', models.FloatField()),
                ('MOD_WRITTEN_COMMUNICATION', models.FloatField()),
                ('MOD_CRITICAL_READING', models.FloatField()),
                ('MOD_ENGLISH', models.FloatField()),
                ('MOD_CITIZENSHIP_COMPETENCES', models.FloatField()),
            ],
            bases=('saber.studentresults',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], max_length=20)),
                ('results', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='saber.studentresults')),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('period', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('SABER11', 'SABER11'), ('SABERPRO', 'SABERPRO')], max_length=20)),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='saber.student')),
            ],
        ),
    ]
