# Generated by Django 5.1 on 2024-08-21 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='institutions',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to='saber.institution'),
            preserve_default=False,
        ),
    ]
