# Generated by Django 5.1 on 2024-08-22 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saber', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegestudent',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_students', to='saber.college'),
        ),
        migrations.AlterField(
            model_name='highschoolstudent',
            name='highschool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highschool_students', to='saber.highschool'),
        ),
    ]
