services:
    postgres:
        image: postgres:latest
        hostname: postgreshost
        env_file:
            - .env
        ports:
            - ${POSTGRES_PORT}:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}",
                ]
            interval: 10s
            timeout: 5s
            retries: 3

        networks:
            - db

    pgadmin:
        image: dpage/pgadmin4
        env_file:
            - .env
        ports:
            - ${PGADMIN_PORT}:80
        depends_on:
            postgres:
                condition: service_healthy
        user: root
        networks:
            - db

    nuxtapp:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        depends_on:
            postgres:
                condition: service_healthy
        networks:
            - db

networks:
    db:

volumes:
    postgres_data:
